FROM node:alpine

WORKDIR /app

# Copy the package.json and package-lock.json to the container
COPY package*.json .n 
COPY package.json /app

# Install app dependencies
RUN npm install

# Copy the rest of the app's source code to the container
COPY . .

# Build the React app
RUN npm run build

# Expose the port on which the app will run
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]